[package]
name = "tuic-quinn"
version.workspace = true
authors.workspace = true
description = "A thin layer on top of quinn to provide functions for TUIC"
categories = ["network-programming"]
keywords = ["network", "proxy", "quic", "tuic"]
edition.workspace = true
rust-version.workspace = true
readme.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
tracing = { version = "0.1", default-features = false}
bytes = { version = "1", default-features = false, features = ["std"] }
quinn = { package = "quinn", git = "https://github.com/spongebob888/quinn-jls", branch = "jls-main", default-features = false, features = ["futures-io"]}
thiserror = { version = "2", default-features = false }
tuic = { path = "../tuic", default-features = false, features = ["async_marshal", "marshal", "model"] }
uuid = { version = "1", default-features = false, features = ["std"] }
tokio = { version = "1", default-features = false, features = ["io-util"] }
eyre = { version = "0" }
