[package]
name = "tuic-client"
version.workspace = true
authors.workspace = true
description = "Minimalistic TUIC client implementation as a reference"
categories = ["network-programming"]
keywords = ["network", "proxy", "quic", "tuic"]
edition.workspace = true
rust-version.workspace = true
readme.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = ["aws-lc-rs"]
ring = ["rustls/ring", "quinn/rustls-ring"]
aws-lc-rs = ["rustls/aws-lc-rs", "quinn/rustls-aws-lc-rs"]
jemallocator = ["tikv-jemallocator"]

[dependencies]
bytes = { version = "1", default-features = false, features = ["std"] }

lexopt = { version = "0.3", default-features = false }
once_cell = { version = "1", default-features = false, features = ["parking_lot", "std"] }

serde = { version = "1", default-features = false, features = ["derive", "std"] }
serde_json = { version = "1", default-features = false, features = ["std"] }
socket2 = { version = "0.5", default-features = false }
socks5-proto = { version = "0.3", default-features = false }
socks5-server = { version = "0.8", default-features = false }

uuid = { version = "1", default-features = false, features = ["serde", "std"] }

# QUIC
quinn = { package = "quinn", git = "https://github.com/spongebob888/quinn-jls", branch = "jls-dev", default-features = false, features = ["runtime-tokio"]}

# TUIC
tuic = { path = "../tuic", default-features = false }
tuic-quinn = { path = "../tuic-quinn", default-features = false }
register-count = { version = "0.1.0", default-features = false, features = ["std"] }

# Tokio/Async
crossbeam-utils = { version = "0.8", default-features = false, features = ["std"] }
tokio = { version = "1", default-features = false, features = ["io-util", "macros", "net", "parking_lot", "rt-multi-thread", "time"] }
tokio-util = { version = "0.7", default-features = false, features = ["compat"] }

# TLS
rustls = { package = "rustls", git = "https://github.com/spongebob888/rustls-jls", branch = "jls-dev", default-features = false, features = ["std"]}
rustls-native-certs = { version = "0.8", default-features = false }
rustls-pemfile = { version = "2", default-features = false, features = ["std"] }

# Error-handling
thiserror = { version = "2", default-features = false }
anyhow = "1"
eyre = { version = "0" }

# Logging
time = { version = "0.3", features = ["macros", "local-offset"] }
humantime = { version = "2", default-features = false }
tracing-subscriber = { version = "0.3", default-features = false, features = ["tracing-log", "std", "local-time", "fmt", "ansi"] }
chrono = "0.4"
tracing = "0.1"

tikv-jemallocator = { version = "0.6", optional = true }